project:
  type: website

execute:
  freeze: auto

book:
  title: "Area Planning Work with R"
  author: "Eli Pousson"
  date: "9/27/2023"
  chapters:
    - index.qmd

# bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

